#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: AWS_development

test:
  <<: *default
  database: AWS_test

#     url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: AWS_production
  username: AWS
  password: <%= ENV['AWS_DATABASE_PASSWORD'] %>
